.github/workflows/first-check.yml
checkstyle.xml
epa-backend.iml
src/main/java/ru/epa/epabackend/model/Employee.java
suppressions.xml

Adding check of work Spring Boot application with DB

ci: check Spring Boot and DB in github action

---

src/main/java/ru/epa/epabackend/dto/task/TaskFullResponseDto.java
src/main/java/ru/epa/epabackend/dto/task/TaskRequestDto.java
src/main/java/ru/epa/epabackend/mapper/TaskMapper.java
src/main/java/ru/epa/epabackend/service/TaskService.java
src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
src/main/java/ru/epa/epabackend/util/StringPatterns.java
src/main/java/ru/epa/epabackend/util/TaskConstants.java

Corrected comments on tasks after the review

fix task after review

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/dto/employee/EmployeeRequestDto.java
src/main/java/ru/epa/epabackend/dto/project/ProjectCreateRequestDto.java
src/main/java/ru/epa/epabackend/dto/task/TaskRequestDto.java
src/main/java/ru/epa/epabackend/util/StringPatterns.java

fix: отработка первых баг-репортов по сотрудникам и проектам 

---

src/main/java/ru/epa/epabackend/controller/admin/AdminCriteriaController.java
src/main/java/ru/epa/epabackend/dto/criteria/RequestCriteriaDto.java

Добавлена валидация названия Criteria.

Fix bag report criteria

---

src/main/java/ru/epa/epabackend/dto/questionnaire/RequestQuestionnaireDto.java
src/main/java/ru/epa/epabackend/service/impl/QuestionnaireServiceImpl.java

Критерии в анкете теперь тоже валидируются

Criteria requirements

---

.github/workflows/first-check.yml
postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
src/main/java/ru/epa/epabackend/dto/evaluation/ResponseEmployeeAssessDto.java
src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
src/main/java/ru/epa/epabackend/service/EmployeeEvaluationService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java

Добавлен список, в котором указан список пользователей с анкетами, требующих оценки

Add list for assess

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
src/main/java/ru/epa/epabackend/service/EmployeeEvaluationService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
src/main/resources/schema.sql

Добавлен эндпоинт получения списка оцененных сотрудников по анкетами

feat(evaluations): add assessed list of employees with questionnaires

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
src/main/java/ru/epa/epabackend/repository/RecommendationRepository.java
src/main/java/ru/epa/epabackend/service/EmployeeEvaluationService.java
src/main/java/ru/epa/epabackend/service/RecommendationService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
src/main/java/ru/epa/epabackend/service/impl/RecommendationServiceImpl.java

2 эндпоинта получения заполненных анкет. Для админа. Для сотрудника. В дизайне это Раздел Оценка ЭС (Оцени сотрудника) -> Оценка поставлена -> заходим в одну из фиолетовых строк

feat(employee-evaluation): get assessed questionnaire

---

src/main/resources/schema.sql

Исправление ограниченности уникальности ключа для таблиц employee_evaluation и recommendation

Fix schema

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
src/main/java/ru/epa/epabackend/service/EmployeeEvaluationService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
src/main/java/ru/epa/epabackend/util/Constants.java

Добавление возможности фильтрации списка сотрудников для оценки и уже оцененных по Фамилии и Имени и по дате

Add search assessment list

---

src/main/java/ru/epa/epabackend/dto/evaluation/RequestAdminEvaluationDto.java

Добавлены ограничения для поля "рекомендация"

Fix restrictions for recommendations

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
src/main/java/ru/epa/epabackend/controller/user/UserEmployeeEvaluationController.java
src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java
src/main/java/ru/epa/epabackend/service/EmployeeEvaluationService.java
src/main/java/ru/epa/epabackend/service/EmployeeService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java

Указание в запросе командного и персонального рейтинга параметра год (year). 
Для просмотра персонального рейтинга сотрудника админом добавлен параметр employeeId. 
Исправлен нативный запрос в репозитории, связанный с группировкой статистики по месяцам

Fix rating statistics

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/user/UserEmployeeController.java
src/main/java/ru/epa/epabackend/dto/employee/ResponseEmployeeFullDto.java
src/main/java/ru/epa/epabackend/model/Employee.java
src/main/java/ru/epa/epabackend/service/EmployeeService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
src/main/resources/schema.sql

Добавление списка с годами, начиная от года регистрации админа до текущего момента
В дизайне это все окна, посвященные аналитике как в админском, так и в пользовательском интерфейсах

Add years from admin creation

---

src/main/java/ru/epa/epabackend/dto/evaluation/RequestAdminEvaluationDto.java
src/main/java/ru/epa/epabackend/dto/evaluation/RequestEmployeeEvaluationDto.java
src/main/java/ru/epa/epabackend/service/EmployeeEvaluationService.java
src/main/java/ru/epa/epabackend/service/EmployeeService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
src/test/java/ru/epa/epabackend/employeeEvaluation/EmployeeEvaluationUnitTests.java

Добавлены проверки сотрудников при получении и отправки оценок.
Сейчас ставить оценки можно только своей группе.
Админ не может оценивать чужих сотрудников и других админов.
Сотрудник может оценивать только своих коллег и только по анкетам созданным своим руководителем.
Админ может оценивать сотрудников только по своим анкетам.

fix: bug post evaluations only his

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/repository/EmployeeEvaluationRepository.java

Исправление работы фильтра
Раньше при фильтре 4 звёзд были анкеты от 3.5 до 4.49. Теперь оь 4 до 4.99 согласно договоренности с Michael

Fix filter by stars

---

src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java

Обновление админа было с ошибкой 400. Теперь ошибка исчезнет

Fix update admin

---

src/main/java/ru/epa/epabackend/controller/admin/AdminEmployeeEvaluationController.java
src/main/java/ru/epa/epabackend/service/EmployeeEvaluationService.java
src/main/java/ru/epa/epabackend/service/QuestionnaireService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeEvaluationServiceImpl.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
src/main/java/ru/epa/epabackend/service/impl/QuestionnaireServiceImpl.java

Добавлены проверки, что админ смотрит только своих сотрудников и свои анкеты

Fix check admin for questionnaire

---

src/main/java/ru/epa/epabackend/repository/TaskRepository.java
src/main/java/ru/epa/epabackend/service/impl/ProjectServiceImpl.java
src/test/java/ru/epa/epabackend/project/ProjectUnitTests.java

Удаление проекта с задачами теперь выдает читаемую ошибку 409 "Невозможно удалить проект, пока к нему привязаны задачи"

Fix delete project with tasks message

---

src/main/java/ru/epa/epabackend/controller/admin/AdminTaskController.java
src/main/java/ru/epa/epabackend/controller/user/UserTaskController.java
src/main/java/ru/epa/epabackend/repository/TaskRepository.java
src/main/java/ru/epa/epabackend/service/TaskService.java
src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java

Добавление фильтрации задач по проектам. 
Добавление просмотра всех задач всех сотрудников админа в пользовательском контроллере

Add filter  of task by project

---

src/main/java/ru/epa/epabackend/dto/criteria/RequestCriteriaDto.java
src/main/java/ru/epa/epabackend/dto/employee/RequestEmployeeDto.java
src/main/java/ru/epa/epabackend/dto/employee/RequestEmployeeShortDto.java
src/main/java/ru/epa/epabackend/dto/employee/RequestJwt.java
src/main/java/ru/epa/epabackend/dto/evaluation/RequestAdminEvaluationDto.java
src/main/java/ru/epa/epabackend/dto/evaluation/RequestEmployeeEvaluationDto.java
src/main/java/ru/epa/epabackend/dto/project/RequestProjectCreateDto.java
src/main/java/ru/epa/epabackend/dto/project/RequestProjectUpdateDto.java
src/main/java/ru/epa/epabackend/dto/task/RequestTaskDto.java
src/main/java/ru/epa/epabackend/dto/technology/RequestTechnologyDto.java
src/main/java/ru/epa/epabackend/exception/ErrorHandler.java

Сообщения ошибок валидации теперь короткие и понятные для пользователей

Fix long errors to short one

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/user/UserEmployeeController.java
src/main/java/ru/epa/epabackend/service/EmployeeService.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java
src/test/java/ru/epa/epabackend/employee/EmployeeTests.java

Мы можем смотреть только сотрудников нашего админа. Было - могли смотреть всех всех сотрудников, включая нашего админа, чужих админов и сотрудников чужих админов

fix(employees): we should see employees of our admin, not another ones

---

src/main/java/ru/epa/epabackend/controller/user/UserTaskController.java
src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java

Исправление расчёта очков за задачи. Если нет задач теперь возвращается вместо null ноль (0). Если сотрудник переводит задачу в done задача завершается и для неё теперь тоже расчитываются баллы и дата завершения задачи

Fix if no points return zero

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/service/impl/AuthenticationServiceImpl.java
src/main/java/ru/epa/epabackend/service/impl/EmployeeServiceImpl.java

Email'ы раньше были регистрозависимыми, то есть можно было создать много пользователей с одним email, у которого отличался лишь регистр символов. Теперь при регистрации, обновлении и авторизации мы переводим email в нижний регистр. То есть пользователь может вводить email в любом регистре и сможет зайти на свой аккаунт. И одному email будет соответствовать один пользователь

Fix processing of email register

---

src/main/java/ru/epa/epabackend/dto/criteria/RequestCriteriaDto.java
src/main/java/ru/epa/epabackend/dto/employee/RequestEmployeeDto.java
src/main/java/ru/epa/epabackend/dto/employee/RequestEmployeeShortDto.java
src/main/java/ru/epa/epabackend/dto/evaluation/RequestAdminEvaluationDto.java
src/main/java/ru/epa/epabackend/dto/task/RequestTaskDto.java

Для описания задачи и рекомендации добавлена возможность вводить спецсимволы.
Обратный слеш удален из сообщений об ошибках.

fix: add special chars for description task and recommendation

---

src/main/java/ru/epa/epabackend/config/JwtAuthenticationFilter.java

Сделали более коротким сообщение об истечении срока токена

fix(jwt): make short and readable message about expiration of jwt token

---

docker-compose.yml

Fix change docker image

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/admin/AdminTaskController.java
src/main/java/ru/epa/epabackend/controller/user/UserTaskController.java
src/main/java/ru/epa/epabackend/repository/TaskRepository.java
src/main/java/ru/epa/epabackend/service/TaskService.java
src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
src/test/java/ru/epa/epabackend/task/employee/TaskEmployeeUnitTests.java

Добавление возможности фильтрации задач по названию или их описанию

feat(tasks): add filter by text

---

docker-compose.yml

fix(secret): delete secret from docker-compose

---

src/main/java/ru/epa/epabackend/controller/admin/AdminProjectController.java
src/main/java/ru/epa/epabackend/dto/project/RequestProjectCreateUpdateDto.java
src/main/java/ru/epa/epabackend/mapper/ProjectMapper.java
src/main/java/ru/epa/epabackend/repository/ProjectRepository.java
src/main/java/ru/epa/epabackend/service/ProjectService.java
src/main/java/ru/epa/epabackend/service/impl/ProjectServiceImpl.java

Сохраняет список проектов разом

Feat save list of projects

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/admin/AdminAnalyticController.java
src/main/java/ru/epa/epabackend/controller/user/UserAnalyticController.java
src/main/java/ru/epa/epabackend/service/AnalyticsService.java
src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
src/test/java/ru/epa/epabackend/analytics/AnalyticsUnitTests.java

Изменение параметров запроса с даты начала и даты окончания на год и месяц для удобства фронтендеров

Fix year month params analytics

---

src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java

Исправление округления при расчёте процентов выполнения задания в срок и не в срок

fix(analytics): fix rounding

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/admin/AdminAnalyticController.java
src/main/java/ru/epa/epabackend/controller/user/UserAnalyticController.java
src/main/java/ru/epa/epabackend/service/AnalyticsService.java
src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
src/test/java/ru/epa/epabackend/analytics/AnalyticsUnitTests.java

Добавление списка годов и списка месяцев для командной и индивидуальной статистики по дедлайнам на основе фактических данных (дат завершения задач)

Add list of years and months for analytics

---

postman/epa.postman_collection.json
src/main/java/ru/epa/epabackend/controller/admin/AdminAnalyticController.java
src/main/java/ru/epa/epabackend/controller/user/UserAnalyticController.java
src/main/java/ru/epa/epabackend/service/AnalyticsService.java
src/main/java/ru/epa/epabackend/service/impl/AnalyticsServiceImpl.java
src/test/java/ru/epa/epabackend/analytics/AnalyticsUnitTests.java

Исправление списка сотрудников со статистикой по дедлайнам. Теперь учитывается, что когда сотрудник создан позже запрашиваемого периода статистики, то он не отображается в списке интивидуальной статистики за этот период

Fix analytics admin individual list

---

src/main/java/ru/epa/epabackend/controller/user/UserTaskController.java
src/main/java/ru/epa/epabackend/service/TaskService.java
src/main/java/ru/epa/epabackend/service/impl/TaskServiceImpl.java
src/test/java/ru/epa/epabackend/task/employee/TaskEmployeeUnitTests.java

Сотрудники могут видеть задачи своих коллег для лучшего понимания, кто чем занимается в рамках проекта и как пересекается с задачами сотрудника

fix(task): employee will see task description of his colleagues
